# Generated by Django 5.0.4 on 2024-05-04 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
