# Generated by Django 4.2.11 on 2024-05-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_perfilusuario_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagem_perfil',
            field=models.ImageField(default='static/logo.jpeg', upload_to=''),
        ),
    ]
